// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACkFpB98mROF67wtM_fAh7Sm-1K8JnVlg',
    appId: '1:603315148809:web:6ebfe61373d5fa227340d8',
    messagingSenderId: '603315148809',
    projectId: 'moodtune-app-99321',
    authDomain: 'moodtune-app-99321.firebaseapp.com',
    storageBucket: 'moodtune-app-99321.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa31SOmrcJudilNmuqmc_3vVVdc8-2suM',
    appId: '1:603315148809:android:3549131e9ef3d1c67340d8',
    messagingSenderId: '603315148809',
    projectId: 'moodtune-app-99321',
    storageBucket: 'moodtune-app-99321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnuISQ7ViDqgaCgC0sjLcuTCRQ1X-iCxs',
    appId: '1:603315148809:ios:917348bb0d3ac3ca7340d8',
    messagingSenderId: '603315148809',
    projectId: 'moodtune-app-99321',
    storageBucket: 'moodtune-app-99321.firebasestorage.app',
    iosBundleId: 'com.example.moodTune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnuISQ7ViDqgaCgC0sjLcuTCRQ1X-iCxs',
    appId: '1:603315148809:ios:917348bb0d3ac3ca7340d8',
    messagingSenderId: '603315148809',
    projectId: 'moodtune-app-99321',
    storageBucket: 'moodtune-app-99321.firebasestorage.app',
    iosBundleId: 'com.example.moodTune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACkFpB98mROF67wtM_fAh7Sm-1K8JnVlg',
    appId: '1:603315148809:web:652bf0832940117b7340d8',
    messagingSenderId: '603315148809',
    projectId: 'moodtune-app-99321',
    authDomain: 'moodtune-app-99321.firebaseapp.com',
    storageBucket: 'moodtune-app-99321.firebasestorage.app',
  );

}